### ISSUE TITLE
Property 'type' does not exist on type 'Event'.ts

### ISSUE THREAD

**Issue by jonath92** [Gr3q/types-cjs#5]
using type() on an event gives the error: 
>    Property 'type' does not exist on type 'Event'

But it exist: https://gjs-docs.gnome.org/clutter8~8_api/clutter.event#method-type

**Comment by Gr3q** [comment]
Yes it is, but it was conflicting with the `type` prop on the more specific event types.

I think I will just inverse it and remove the prop instead from all the other ones.

**Comment by jonath92** [comment]
close as fixed
