### ISSUE TITLE
Why does connecting to a Property Change Notification requires a number as return type?

### ISSUE THREAD

**Issue by jonath92** [Gr3q/types-cjs#6]
Currently you must return a number when connecting to a property change with `notify::[property]`: 

```
widget.connect('notify::hover, () => {
   widget.change_style_pseudo_class('active', widget.hover)
   return 1 // why this line needed?
)
``` 

In the tutorial they are returning nothing: https://gjs.guide/guides/gobject/basics.html#property-change-notification ...

**Comment by Gr3q** [comment]
Yeah, I already commented on your PR, it is a mistake (typo) on my part, I will fix this tomorrow.

**Comment by jonath92** [comment]
close as fixed
